# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from travel_billing.main_manual import InvoicePage
class DashboardFull(QMainWindow):
    def __init__(self):
        super().__init__()
        self.invoice_page = InvoicePage()
        self.setCentralWidget(self.invoice_page)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 490, 55, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 330, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.add_bill_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_bill_button.setGeometry(QtCore.QRect(210, 200, 93, 28))
        self.add_bill_button.setObjectName("add_bill_button")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(460, 190, 256, 192))
        self.tableView.setObjectName("tableView")
        self.view_records_button = QtWidgets.QPushButton(self.centralwidget)
        self.view_records_button.setGeometry(QtCore.QRect(80, 280, 93, 28))
        self.view_records_button.setObjectName("view_records_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.add_bill_button.setText(_translate("MainWindow", "New Bill"))
        self.view_records_button.setText(_translate("MainWindow", "View Records"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
from PyQt5 import QtWidgets
from travel_billing.main_manual import InvoicePage

class DashboardFull(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Travel Agency - Billing Software")
        self.resize(1200, 700)

        # Create the manual invoice page
        self.invoice_page = InvoicePage()
        self.setCentralWidget(self.invoice_page)

        # Optional: Grey background style
        self.setStyleSheet("""
            QMainWindow {
                background-color: #f0f0f0;
            }
            QPushButton {
                background-color: #d9d9d9;
                border-radius: 5px;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #c0c0c0;
            }
        """)

if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = DashboardFull()
    window.show()
    app.exec_()
# ffrom PyQt5 import QtWidgets
# from PyQt5 import QtWidgets
# from travel_billing.main_manual import InvoicePage

# class DashboardFull(QtWidgets.QMainWindow):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Travel Agency - Billing Software")
#         self.resize(1200, 700)

#         # Create InvoicePage object (from main_manual.py)
#         self.invoice_page = InvoicePage()

#         # Put it inside a container layout
#         central_widget = QtWidgets.QWidget()
#         layout = QtWidgets.QHBoxLayout(central_widget)

#         # Sidebar (optional) — comment out if not needed
#         sidebar = QtWidgets.QFrame()
#         sidebar.setFixedWidth(180)
#         sidebar.setStyleSheet("background-color: #111;")

#         # Add sidebar + main content
#         layout.addWidget(sidebar)
#         layout.addWidget(self.invoice_page)

#         # Set as central widget
#         self.setCentralWidget(central_widget)
