# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'travel_billing/ui/billing_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 30, 111, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 55, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(180, 40, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 70, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 100, 113, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 130, 113, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(190, 130, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.pushButton.clicked.connect(self.save_data)
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Customer Name"))
        self.label_2.setText(_translate("Form", "Supplier Name"))
        self.label_3.setText(_translate("Form", "Total Amount"))
        self.label_4.setText(_translate("Form", "Date"))
        self.pushButton.setText(_translate("Form", "save"))
    # def save_data(self):
    #     customer = self.lineEdit.text()
    #     supplier = self.lineEdit_2.text()
    #     total = self.lineEdit_3.text()
    #     date = self.dateEdit.date().toString("dd/MM/yyyy")

    #     print(f"Customer: {customer}")
    #     print(f"Supplier: {supplier}")
    #     print(f"Total Amount: {total}")
    #     print(f"Date: {date}")
    import sqlite3

    # def save_data(self):
    # import sqlite3

    # try:
    #     # --- Step 1: Get data from the form ---
    #     customer = self.lineEdit.text()
    #     supplier = self.lineEdit_2.text()
    #     total = self.lineEdit_3.text()
    #     date = self.dateEdit.date().toString("dd/MM/yyyy")

    #     print("Customer:", customer)
    #     print("Supplier:", supplier)
    #     print("Total:", total)
    #     print("Date:", date)

    #     # --- Step 2: Connect to database ---
    #     conn = sqlite3.connect("travel_billing.db")
    #     cursor = conn.cursor()

    #     # --- Step 3: Create table if not exists ---
    #     cursor.execute("""
    #         CREATE TABLE IF NOT EXISTS bills (
    #             id INTEGER PRIMARY KEY AUTOINCREMENT,
    #             customer TEXT,
    #             supplier TEXT,
    #             total REAL,
    #             date TEXT
    #         )
    #     """)

    #     # --- Step 4: Insert data ---
    #     cursor.execute("""
    #         INSERT INTO bills (customer, supplier, total, date)
    #         VALUES (?, ?, ?, ?)
    #     """, (customer, supplier, total, date))

    #     # --- Step 5: Commit and close ---
    #     conn.commit()
    #     conn.close()

    #     print("✅ Data saved successfully to database!")

    # except Exception as e:
    #     print("❌ Error saving data:", e)
    # def save_data(self):
    #     customer = self.lineEdit.text()
    #     supplier = self.lineEdit_2.text()
    #     total = self.lineEdit_3.text()
    #     date = self.dateEdit.date().toString("dd/MM/yyyy")

    #     print(f"Customer: {customer}")
    #     print(f"Supplier: {supplier}")
    #     print(f"Total Amount: {total}")
    #     print(f"Date: {date}")

    
    # try:
    #     conn = sqlite3.connect("travel_billing.db")  # Connect to your DB
    #     cursor = conn.cursor()

    #     # Create table if not exists
    #     cursor.execute("""
    #         CREATE TABLE IF NOT EXISTS bills (
    #             id INTEGER PRIMARY KEY AUTOINCREMENT,
    #             customer TEXT,
    #             supplier TEXT,
    #             total REAL,
    #             date TEXT
    #         )
    #     """)

    #     # Insert data
    #     cursor.execute("""
    #         INSERT INTO bills (customer, supplier, total, date)
    #         VALUES (?, ?, ?, ?)
    #     """, (customer, supplier, total, date))

    #     conn.commit()
    #     conn.close()
    #     print("✅ Data saved successfully to database!")

    # except Exception as e:
    #     print("❌ Error saving data:", e)

    def save_data(self):
      import sqlite3

    # --- Step 1: Get values from the form ---
      customer = self.lineEdit.text()
      supplier = self.lineEdit_2.text()
      total = self.lineEdit_3.text()
      date = self.dateEdit.date().toString("dd/MM/yyyy")

      print(f"Customer: {customer}")
      print(f"Supplier: {supplier}")
      print(f"Total Amount: {total}")
      print(f"Date: {date}")

      try:
        # --- Step 2: Connect to database ---
          conn = sqlite3.connect("travel_billing.db")
          cursor = conn.cursor()

        # --- Step 3: Create table if not exists ---
          cursor.execute("""
            CREATE TABLE IF NOT EXISTS bills (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                customer TEXT,
                supplier TEXT,
                total REAL,
                date TEXT
            )
        """)

        # --- Step 4: Insert data ---
          cursor.execute("""
            INSERT INTO bills (customer, supplier, total, date)
            VALUES (?, ?, ?, ?)
        """, (customer, supplier, total, date))

          conn.commit()
          conn.close()

          print("✅ Data saved successfully to database!")

      except Exception as e:
        print("❌ Error saving data:", e)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
