# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from travel_billing.main_manual import InvoicePage
# from main_manual import InvoicePage


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 490, 55, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(220, 330, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.add_bill_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_bill_button.setGeometry(QtCore.QRect(210, 200, 93, 28))
        self.add_bill_button.setObjectName("add_bill_button")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(460, 190, 256, 192))
        self.tableView.setObjectName("tableView")
        self.view_records_button = QtWidgets.QPushButton(self.centralwidget)
        self.view_records_button.setGeometry(QtCore.QRect(80, 280, 93, 28))
        self.view_records_button.setObjectName("view_records_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.add_bill_button.setText(_translate("MainWindow", "New Bill"))
        self.view_records_button.setText(_translate("MainWindow", "View Records"))
